server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://142.93.214.116/ecommerce
    username: axowave
    password: eeeaf30cGETEVWf2sv
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
    show-sql: true

logging:

  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.hibernate: info
    org.springframework:
      security: info