server:
  port: 8080

spring:
  cache:
    type: redis

  datasource:
    url: jdbc:mysql://localhost:8889/spring_jwt_security
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

logging:

  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.hibernate: info
    org.springframework:
      security: info